### ISSUE TITLE
Data for emulator

### ISSUE THREAD

**Issue by kmilonas** [CLIMADA-project/climada_python#118]
The tutorial for the emulator states that the relevant files (with cyclone tracks) are stored in CLIMADA_DIR/data/emulator. I did not find that subdirectory of my Climada data directory. Are they available for download from somewhere else?

Using Climada 1.5.1.

Thanks

**Comment by tovogt** [comment]
The tutorial included with CLIMADA 1.5.1 is not clear enough and also kind of misleading in some other aspects. That's why I rewrote it for the next release. I strongly recommend to use that updated version instead: https://github.com/CLIMADA-project/climada_python/blob/tutorial_update/doc/tutorial/climada_hazard_emulator.ipynb

Unfortunately, most of the data needed to run the tutorial notebook is external and not part of the CLIMADA repository. You find some instructions on how to obtain or re-generate that data at the end of the updated tutorial notebook.
