### ISSUE TITLE
TCTracks.read_ibtracks_netcdf agency auto-choice

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#119]
Reading the IBTracks is extremely slow when the provider is not specified. It seems like the function loops through all tracks and providers and then chooses. Why? How should the default/best provider be chosen?

**Comment by bguillod** [comment]
I agree with your comment to some extent. Here is my understanding and some follow-up questions/comments:

- On the one hand the current approach allows to use any provider for each track, thereby not excluding tracks without data for a given provider if data from another provider is available for that track - I think this is where the advantage lies. To know this however there is probably no alternative to going through the providers one after another until data is found...

- On the other hand, the maximum sustained wind speed is using different averaging time for different agencies, so combining data from several providers is not very recommended (see https://www.ncdc.noaa.gov/ibtracs/pdf/IBTrACS_version4_Technical_Details.pdf). Therefore, I prefer to always specify a provider. That being said, the TropCyclone module does not use max_sustained_wind to derive the wind fields, so that's kind of ok, but it could be misleading when plotting the tracks.

- Note that also other variables (incl. pressure) might include "jumps" in the data when combining providers. This would also speak for forcing to fix the provider.

- Perhaps an easy alternative would be to specify a default provider (e.g. "usa"), but let the user specifically pass "combined" as a provider if s/he really wants data combined from providers?

**Comment by chahank** [comment]
Thanks for the input. Do you know whether if a track is found for several providers, which one is chosen?

**Comment by bguillod** [comment]
My understanding is that this is defined there:
https://github.com/CLIMADA-project/climada_python/blob/31ed3abcf7450d6b4dff3761f8e737a64bdb05a6/climada/hazard/tc_tracks.py#L1575

as well as here:
https://github.com/CLIMADA-project/climada_python/blob/31ed3abcf7450d6b4dff3761f8e737a64bdb05a6/climada/hazard/tc_tracks.py#L354

However I must say I don't have time to really understand what it exactly does. It might mix agencies even for a given track, I'm not sure. You might be quicker than me at finding out the details. Or perhaps @tovogt knows it exactly (if I remember well he coded this, though I might be wrong).

**Comment by tovogt** [comment]
Yes, the logic is mixing agencies for a given track and variable. The order or preference is specified here:
https://github.com/CLIMADA-project/climada_python/blob/31ed3abcf7450d6b4dff3761f8e737a64bdb05a6/climada/hazard/tc_tracks.py#L86-L90

For all variables (wind speed, central pressure, radius of maximum wind etc.) separately, it's just going through that list and chooses the first agency for which there is a valid value.

The values of two subsequent time steps might be from different agencies. I'm not really happy with that because it actually leads to zig-zag values. Usually, the official WMO values are in 6-hour time steps and then the procedure fills the missing 3-hour time steps by whichever agency has valid values for those steps.

Anyway, is this issue about the procedure being "slow" or about the procedure being "bad"? Because it seems to me like this should be separate discussions...

**Comment by chahank** [comment]
Thanks for the explanations about what it is doing actually. I agree that there are two questions here:
- is it a good way to proceed?
- if yes, is it well (fast/efficiently) implemented?
But I would say that both are not fully independent. Now it seems to me that the algorithm is neither optimal in the sense of 'good' nor 'efficient'.

**Comment by tovogt** [comment]
How do you see that it's not efficient?

**Comment by chahank** [comment]
I did not say that it is not efficiently implemented, I said the algorithm is maybe not the best in efficiency. Your example is perfect: does it make sense to add points every 3 hours if one provider has it only all  6 hours? If not, then the computation time would also be halfed.

**Comment by tovogt** [comment]
But then it would do something different. You wouldn't just change the implementation, but also the procedure AND the result.

**Comment by chahank** [comment]
Yes, precisely.

**Comment by tovogt** [comment]
If you say that the procedure should be changed because it's a strange idea to mix agencies in this way, I agree. If you say that we might even gain in computational cost from changing the procedure, I agree as well.

But if you say that the implementation of the current procedure is inefficient, I want to know where it is inefficient.

**Comment by chahank** [comment]
Then we agree :D

**Comment by tovogt** [comment]
Okay, so when we are talking about changing the procedure, I would propose at least these features:

1. Add the possibility to enforce that the official WMO agency is always selected. This will always lead to 6-hour time steps because that's the "official" reporting frequency.
1. Add the possibility to enfoce the official WMO agency, but not only for the 6-hour time steps, but also for the 3-hour time steps for which the official agency reported these values.
1. Add the possibility to specify a list as the `provider` argument. For each storm, the first agency in the list is chosen for which not all data points are invalid.

This would enforce that each separate track data set is either derived from a single agency or from the official agencies, but not from some complicated selection algorithm that might change the agency in each time step in the worst case. However, note that this would probably lead to a lot of missing values (that might be filled by bad estimations).

For the missing variables (especially radius) it would be good to have a way to obtain those from a different agency. But not per-time-step, but for the whole track (for consistency *within* each variable):

4. For each storm, if any variable (such as radius of maximum wind) is not reported by the agency selected according to the selected rule (1-3 above), obtain that variable from the first agency in the list that has it.
5. If a variable (such as radius of maximum wind) has NaNs in some time steps (but not all) interpolate to fill the gaps.

However, note that I wouldn't be too optimistic that these procedures will necessary be much faster than the current in the end.

**Comment by chahank** [comment]
Yes, this sounds like a great way forward. I think if someone uses only 1-3, this would already be a bit better than now choosing a single provider, yet remains fast. For the best result (applying 4-5), I agree that the procedure might not be faster. Overall I think this could be a win-win (better and faster in some cases).

**Comment by tovogt** [comment]
To have an impression of performance, I run some tests myself: When I read all tracks between 1980 and 2015, the time per track is roughly equivalent (10% difference) when comparing an explicit provider and the automatic choice of provider. Here is the code with output:

```
tracks = TCTracks()
t = %timeit -n1 -r1 -o tracks.read_ibtracs_netcdf(year_range=(1980, 2015), provider="usa")
print(t.average / tracks.size)
```
Output: 0.019327253824850416
```
tracks = TCTracks()
t = %timeit -n1 -r1 -o tracks.read_ibtracs_netcdf(year_range=(1980, 2015))
print(t.average / tracks.size)
```
Output: 0.02128298519767826

However, the number of tracks is much larger when no provider is specified (3359 vs. 1827) since many track records are missing for the chosen provider.

So, if you create an issue about performance, please do run performance tests before and specify the exact run parameters and the resulting difference in performance. A difference of 10% is not "very slow". This is not a good basis for a fruitful discussion about possible performance improvements.

**Comment by chahank** [comment]
Hi Thomas,
Thanks for the speedtest. I did one too (should definitely have posted it!) and the difference was more than a factor 10. But, seeing your result, I will redo it to see whether something extra was causing trouble.

**Comment by chahank** [comment]
So, I re-did a speed test and I get a significant difference  I would say, even when correcting for the different number of tracks returned.

time: 17.6s
```
tc_tracks1 = TCTracks()
tc_tracks1.read_ibtracs_netcdf(provider='usa', basin='WP', year_range=(1950, 2020)) 
```

time: 412s
```
tc_tracks2 = TCTracks()
tc_tracks2.read_ibtracs_netcdf(basin='WP', year_range=(1950, 2020)) 
```

So, the difference is a factor ~23. Buuuuut, at first I did not normalize for the different number of tracks involved. Doing so, I get:

time: 0.029
time: 0.169

The time difference is still a factor: 5.8

**Comment by tovogt** [comment]
That's a bug in xarray apparently. The following line is extremely slow when a filtering by basin has been applied previously:
https://github.com/CLIMADA-project/climada_python/blob/3d6200e4dd730c7d70de3a59045395d70be135d5/climada/hazard/tc_tracks.py#L1597
You will notice that your test will result in a completely different timing when you remove the `basin='WP'` argument from the call.

I added a new branch `feature/tc_read_ibtracs` that I will use to implement my suggestions (https://github.com/CLIMADA-project/climada_python/issues/119#issuecomment-764838628). As a first step I pushed a fix for your particular performance issue: 
https://github.com/CLIMADA-project/climada_python/blob/6ae4e76f01e51f62942c3dee0b1f30124f71a9ec/climada/hazard/tc_tracks.py#L337-L340
However, this is only for demonstration. I will completely rewrite the agency- and provider-related stuff before creating a PR.

**Comment by bguillod** [comment]
Just to jump in again, but I do so so that this does not get forgotten, and it's not about performance but about whether mixing up data from various agencies is a good idea:

What I don't like in mixing up agencies is that the wind speed definition can differ: averaging time can vary from 1-minute (US agencies) to 10-minutes (as already mentioned in my previous comment). Hence, maximum_sustained_wind will be defined differently from track to track (or point to point in the worst case), on average expect 1-min values to be roughly 12% higher than 10-minutes values - which can be a lot!

Admittedly, this should not impact the holland wind field too much since these are based on pressure and other variables, not wind speed. HOWEVER this is not even 100% true, because the TC category is based on maximum_sustained_wind and for instance the landfall decay correction depends on category. I did not think about that earlier so thought it is useful to mention it here for reference.

**Comment by tovogt** [comment]
Yes, I didn't forget this and will include a linear scaling in the rewrite.

**Comment by tovogt** [comment]
See #123 for my implementation of the proposed changes in https://github.com/CLIMADA-project/climada_python/issues/119#issuecomment-764838628
