### ISSUE TITLE
Source for drought impact function default calibration?

### ISSUE THREAD

**Issue by krismilonas** [CLIMADA-project/climada_python#127]
Hi, I'm trying to understand how the presets in climada.entity.impact_funcs.drought.IFDrought are set. Is there some study you could point me to which explains the calibration?

Thanks

**Comment by sameberenz** [comment]
Thank you for your interest! The impact function defaults were the result of a Master Thesis by Carmen Steinmann and Veronica Bozzini. The functions were fitted for a selection of historical droughts and the hazard intensity used was SPEI6.
Since the thesis is not public, please get in contact with the authors directly for more information: https://wcr.ethz.ch/people/research-assistants/carmen-steinmann.html
