### ISSUE TITLE
u_coord.points_to_raster: bounds when crossing antimeridian

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#139]
For points sets that are distributed across the International Date Line, the raster will contain all longitudes (-180, 180) because of
```
# construct raster
xmin, ymin, xmax, ymax = (points_df.longitude.min(), points_df.latitude.min(),
                          points_df.longitude.max(), points_df.latitude.max())
```
As a consequence, using for example `impact.plot_raster_eai_exposure()` for the USA will contain all longitudes instead of only the USA.

Question: how does one make a raster which crosses the International Date Line with rasterio?

**Comment by tovogt** [comment]
The way to go is to represent longitudes not in the interval [-180,180], but in some other interval of length 360, such as [0, 360].  For example, you could do something like this:
```
xmin, ymin, xmax, ymax = latlon_bounds(points_df.latitude.values, points_df.longitude.values)
x_mid = 0.5 * (xmin + xmax)
```
After that, you  have to renormalize all your x-coordinates (in `df_poly` and `points_df`) using `lon_normalize(..., center=x_mid)`.

**Comment by bguillod** [comment]
We had the same issue in another context (with R and leaflet) and ended up creating a list containing either a single raster (if within -180 to +180) or two rasters (if crossing the +/-180, one e.g. between 160 and 180 and one between e.g. -180 and -170, if you raster goes from +160 to -170 through the antimeridian).
Either way, you have to make sure the functionalities using your object will get the correct coordinates or be able to deal with shifted coordinates. The tricky part is often to determine whether the range is -180 to +180 because it crosses the anti-meridian or whether your raster should cover the whole globe. But perhaps the reply from @tovogt above is sufficient for your needs.

**Comment by tovogt** [comment]
Ideally, a function that gets longitudinal values as an input and requires them to be normalized to [-180, 180] should mention it in the docstring. Otherwise, functions should automatically normalize longitudinal input values according to their needs. We have the util-functions to do that, it's not that hard actually.

But you are right: At the moment, there are a lot of functions in CLIMADA that silently assume longitudinal values to be in [-180, 180] and will do crazy things for stuff crossing the antimeridian. I think, we should aim at improving all of those functions step by step so that they can handle those cases appropriately.

**Comment by chahank** [comment]
Hmm does this mean one cannot solve this directly in the util function, but one hast to modify each plotting function since the data must be renomarlized?

**Comment by tovogt** [comment]
No, we can modify `points_to_raster` to renormalize longitude values.

**Comment by tovogt** [comment]
If your data already comes as a GeoDataFrame with EPSG:4326 (this is the default), you can renormalize longitudinal coordinates using `df.to_crs({"init": "epsg:4326", "lon_wrap": mid_lon})`.

**Comment by tovogt** [comment]
Please continue the discussion for other plotting functions in #153
