### ISSUE TITLE
Plot functions: better antimeridian handling

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#153]
When data is concentrated in a region close to the antimeridian (like Alaska, Hawaii or Fiji), many of CLIMADA's plotting functions fall back to plotting the whole globe (longitudes from -180 till 180). We fixed this for some of the plotting functions in #145, but there are still a lot to check.

The problem with most of CLIMADA's plot functions is that they assume the same cartopy projection for the data as for the plot (axis). But the data might be given in a projection different from the axis projection. Using this, the axis projection can shift the 0-longitude to a different location without any need to touch the data itself.

Here is a list of plotting functions that we fixed already:
* `util.plot.geo_bin_from_array`
* `util.plot.geo_im_from_array`
* `Centroids.plot`
* `TCTracks.plot`
* `Exposures.plot_raster`

Here is a list of plotting functions that I haven't checked:
* `util.plot.geo_scatter_from_array` (fixed in #204)
* `Impact.video_direct_impact`
* `RelativeCropyield.plot_time_series`
* `TropCyclone.video_intensity`

If a plotting function calls the functions in `util.plot`, I didn't explicitly list it here.

Are there any other functions we have to add to the list?

**Comment by chahank** [comment]
While doing some plotting, I realized that since CLIMADA functions only return the axis and not the figure, one does not have access to several plot handles because the axis are very directly linked to their figure. While before the change it was possible to do:

```
fig, ax = u_plot.make_map()
impact.plot_raster_eai_exposure(axis=ax)
ax.set_title('my custom title')
fig.save_fig('filename')
```

this is not possible anymore, as the projection returned by `u_plot.make_map()` will be wrong.

One could think that 

```
fig = plt.figure()
ax = impact.plot_raster_eai_exposure()
ax.set_title('my custom title')
fig.add_axes(ax)
```
or
```
fig = plt.figure()
ax = impact.plot_raster_eai_exposure()
ax.set_title('my custom title')
fig.axes.append(ax)
```

could work, but this seems to not be possible anymore with the latest versions of matplotlib.
https://stackoverflow.com/questions/6309472/matplotlib-can-i-create-axessubplot-objects-then-add-them-to-a-figure-instance

One way to solve this is to return both the figure and the axes. Any other suggestions?

**Comment by davidnbresch** [comment]
return both figure and axis, unless there is a more elegant solution. Especially looking forward, i.e. to modify figures and axes therein, also for use in eg GUIs, it is key that one does get these ‘handles’ back.

**Comment by gabrielaznar** [comment]
Hi @chahank. I just ran into this comment about the figure and axis and wanted to give one explanation without knowing exactly what you want to do.
So, fig=ax.get_figure() is not working for your problem? I set the functions to return just the axis because the figure could be obtained easily from the axis. This way it was safer to avoid modifying one without knowing you’re modifying the other one.
Best wishes!

**Comment by chahank** [comment]
Hi @gabrielaznar thanks for the advice! I didn't know this one. 

I just tried it, but unfortunately 

```
ax = imp.plot_raster_eai_exposure(label=xlabel)
ax.set_title('my_title')
fig = ax.get_figure()
fig.savefig("my_fig.pn")
```
does not work as intended. The figure seems not to be sized the same as the ax. Here is an example:

![Imp_FJI_year2020_rcp26](https://user-images.githubusercontent.com/7040169/108636772-c2a60800-7487-11eb-8bc2-dc14acd4ee9e.png)

I do not know however whether this is due to the recent changes to how the axes are handled or not. Will have to investigate.

**Comment by gabrielaznar** [comment]
I had this issue when saving, related to the savefig command. It usually worked using the option bbox_inches=‘tight’ of savefig, and also adding format= (with ‘pdf’ worked fine). I would give it a try!

**Comment by davidnbresch** [comment]
Uuhhh... ;-)

Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch
dbresch@meteoswiss.ch
office: +41 44 632 77 87
mobile: +41 79 770 15 92
skype: davidnbresch
zoom: https://ethz.zoom.us/my/dbresch
https://www.usys.ethz.ch/en/people/profile.david-bresch.html, http://www.wcr.ethz.ch

**Comment by tovogt** [comment]
Please continue the discussion about the handling of figure and axes in #154
