### ISSUE TITLE
test_fraction_on_land fails on develop in new environment

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#156]
The test climada.hazard.test.test_tc_surge_bathtub.TestTCSurgeBathtub.test_fraction_on_land fails since commit f0adbe7920ff90ae68f9ebce5e99dd976c9bd7c7.

I assume, it is related to the updated rasterio and/or gdal versions, but I'm not 100% sure.

That the test fails is clear and the reasons are obvious. In the shore regions (fraction >0 <1) the values returned from `rasterio.warp.reproject` are different now. What is not clear is: are the new values any worse than the old ones? To me they look just as reasonable as the old ones, but I'm not familiar with the methods.

@tovogt: It would be great if you could have a look at this.

**Comment by tovogt** [comment]
I need more information from you: Which version of GDAL and rasterio is used in the Jenkins environment? Maybe you can directly provide me with the whole conda environment used in Jenkins. I can't reproduce this with rasterio=1.1.5 and gdal=3.0.4 on my Ubuntu 20.04 machine. Thanks in advance for your help!

**Comment by tovogt** [comment]
Okay, I was able to reproduce it now: In fact, the problem you describe is caused by a non-trivial change to the `average` resampling method in GDAL 3.1: https://github.com/OSGeo/gdal/pull/2363 I will adapt the tests accordingly. 

If you're wondering about the versions of rasterio and gdal I mentioned above: After you changed the requirements, I applied `conda env update` instead of creating it from scratch. When creating a new environment from scratch with the new requirements files, you get different versions of rasterio and gdal.
