### ISSUE TITLE
Wrong gap-filling of roci in read_ibtracs_netcdf?

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#169]
I am concerned about the following two lines:
https://github.com/CLIMADA-project/climada_python/blob/a4e42a6cec7c9544cdd5bc0afdb19de748a6b94c/climada/hazard/tc_tracks.py#L540-L541

Looking at function estimate_roci, it should take central pressure (`tracks_ds.pres`), and not radius of maximum wind, as a second input. Or is this wrongly documented in that function?
Also, why is `roci` set to at least `rmw`? Is there any physical reason? I cannot recall that this limit was set in the past.

**Comment by tovogt** [comment]
See #170 for the fix.

This is not really a big thing, because the ROCI isn't used in the wind field calculation.

For your second question: The whole point of the ROCI is to estimate the total vortex size. Of course, the ROCI will always be larger than the radius of maximum wind, because the maximum wind must, by defintion, be attained within the storm vortex.

**Comment by bguillod** [comment]
Thanks for the quick fix and the clarification on the `np.fmax` statement!
