### ISSUE TITLE
climada_hazard_emulator tutorial fails because of missing file

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#182]
In Jenkins climada_notebook project the test `NBTest.climada_hazard_emulator` fails in cell 3:

```python
def ibtracs_windfields(region, period=None):
    ...
    fname = 'GLB_0360as_hazard_1950-2015.mat'
    path = EMULATOR_DATA_DIR.joinpath("windfields", fname)
    ...
```

Where the file .../demo/data/emulator/windfields/GLB_0360as_hazard_1950-2015.mat is missing.

**Comment by tovogt** [comment]
First of all, the code sample is from the old version of the notebook. The `tutorial_update` branch contains a complete rewrite. The updated version also contains an exact list of all the files required and how to obtain those.

Secondly, the required files are 800 MB in size (~300 MB when gzipped). Furthermore, two of the most important ingredients are only available for research use upon request. For internal testing purposes on Jenkins, I can provide you with the files.

Finally, for potential CLIMADA users, it would be ideal if the notebook could be executed with openly available data. @chahank Would you please provide me with the IBTrACS and synthetic windfields that are planned to be released as part of the open CLIMADA data API so that I can try to adapt the tutorial notebook based on that?

**Comment by tovogt** [comment]
Maybe we can reopen this in https://github.com/CLIMADA-project/climada_petals if really necessary?
