### ISSUE TITLE
Tropical Cyclone: max_angle

### ISSUE THREAD

**Issue by SchmidDavid** [CLIMADA-project/climada_python#19]
Dear Climada Team,

Could you please help me to better understand the tropical cyclone calc_random_walk parameter "max_angle"? 

a) If pi is undirected, as stated in the code, I would expect a random spread of the tracks in all directions. Instead the probabilistic tracks are rather narrow. 

b) If I set max_angle to 0 I would expect that every replication is the same as the original track. Instead all the replications move somehow parallel northward (is it maybe because cosinus of 0 is 1?). 

c) I don't understand that e.g. pi/10 returns a larger spread of probabilistic storms than e.g. pi/4. Why does a smaller angle allow for more variation?

Thank you for your help and best regards,
David

**Comment by sameberenz** [comment]
Hi David
thanks for your request. While Thomas and me have not been involved in the development of the random walk algorithms, we can try to adress this issue.
After having a look at the code, we realized that the description of the method and the parameters needs to be expanded. We are currently working to do so. But since we are new to the code as well, this can still take some days.

As for now, here is what I think max_angle does, based on my analysis of the code:
For each timestep, the position of a synthetic track is "wiggled" a little bit, i.e. deviated from its original position and this change is summed up with cumsum() for each consecutive timestep of the track.

The amplitude of the wiggle is defined by ens_amp and the direction of change by max_angle in combination with a random numer (0 to 1) per time step. Here are two plots of the range in change in the two directions that is possible for each parameter value of max_angle (for the northern hemisphere, with ens_amp set to 1 for simplicity):

![TC_rnd_walk_LON](https://user-images.githubusercontent.com/27805268/82332317-85d34f00-99e5-11ea-9bc8-dc9c50c86e52.png)

![TC_rnd_walk_LAT](https://user-images.githubusercontent.com/27805268/82332329-8966d600-99e5-11ea-989c-9ce5ef1222aa.png)


As you can see, there is no randomness for max_angle=0, but rather a northward shift of the track. This is indeed due to a cosinus function applied in the algorithm. Actually, the plots show a poleward direction of sythetic tracks for 0<=max_angle<=pi. This is visible in plots of synthetic ensembles for small values of max_angle. Here are three examples, with max_angle = pi/300, pi/70, and pi/10 (which is the default value):

![Screenshot 2020-05-19 at 15 38 37](https://user-images.githubusercontent.com/27805268/82333333-e44cfd00-99e6-11ea-97a7-d395133545bb.png)


As we are currently doublechecking and updating the description, here is my current suggestion to explain the method calc_random_walk():



> calc_random_walk(): Generate synthetic tracks based on directed random walk. An ensemble of tracks is computed for every track contained. Please note that there is a bias towards higher latitudes in the random wiggle. The wiggles are applied for each timestep. Please consider using equal_timestep() for unification before generating synthetic tracks. Be careful when changing ens_amp and max_angle and test changes of the parameter values before application.
> 
>     Parameters:
>         ens_size (int, optional): number of ensemble members per original track.
>             Default 9.
>         ens_amp0 (float, optional): amplitude of max random starting point
>             shift in decimal degree (longitude and latitude). Default: 1.5
>         max_angle (float, optional): maximum angle of variation. Default: pi/10.
>             - max_angle=pi results in undirected random wiggles of track;
>             - max_angle=0 (or very close to 0) results in non-random synthetic tracks with constant shift to higher latitudes (not recommended)
>             - max_angle=pi/4 results in random angles within one quadrant, also with a poleward bias;
>             - for 0<max_angle<pi/2, the change in latitude is always toward higher latitudes, i.e. poleward.
>         ens_amp (float, optional): amplitude of random walk wiggles in
>             decimal degree (longitude and latitude). Default: 0.1
>         seed (int, optional): random number generator seed for replicability of random walk. Put negative
>             value if you don't want to use it. Default: configuration file
>         decay (bool, optional): compute land decay in probabilistic tracks.
>             Default: True


It would be great to hear from you whether this descirpition fits your interpretation and how the description could be futher improved.

**Comment by sameberenz** [comment]
We have updated the docstring of the method **calc_random_walk()** on the _develop_ branch in commit https://github.com/CLIMADA-project/climada_python/commit/580519a9addf37bde183727b62a04a1d9e0949e8 .
The master branch will be updated soon.

**Comment by sameberenz** [comment]
Hi Celina

**Comment by bguillod** [comment]
I personally think the implementation is misleading. My understanding is that the angle variation should be an angle added to the track line angle. Instead, it appears to be **the angle of a direction of perturbation, with 0 meaning "northward" (or southward if latitude is <0), independently of the track**. However, without knowing where the algorithm comes from it is difficult to assess whether that's intended. Would a proposed modified version for this be helpful, and if so, does anyone (e.g. @davidnbresch?)  has a reference of algorithm description to be used?
