### ISSUE TITLE
uncertainty tutorial breaks readthedocs build

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#203]
readthedocs has trouble to create pdf files, seemingly some kind of memory excedence:
https://readthedocs.org/projects/climada-python/builds/13468800/

To reproduce locally
```
cd doc
make pdf
```

**Comment by chahank** [comment]
I was not able to reproduce the error. However, I was also not able to build the `env_docs` environment. Trying fixing things to use `make pdf`, I managed to let it run. It returned a `latex error 1`. In the `climada.log` the error is given as `! LaTeX Error: Too deeply nested.` which is not very helpful.

**Comment by scem** [comment]
The env_docs.yml file is the output of `conda env export env_climada` - after installation of additional packages `nbsphinx`, `nb_conda` and `nb_conda_kernels`. This is because with an "open" environment definition, the build used to run out of memory.
Hence the "ordinary" climada environment should be fine to use - after installation of the named packages.

However, on Windows, I get a similar error message like the one at [readthedocs.org](https://readthedocs.org/projects/climada-python/builds/13468800/), and nothiing about `deeply nested`. Perhaps the latter happens only after the `Tex capacity` problem has got overcome.

And yes - helpful is different. The only approach I can think of ist to localize the problem by cell deletion. Which is tedious.

**Comment by chahank** [comment]
I think this is solved right @emanuel-schmid ?

**Comment by emanuel-schmid** [comment]
Yes. For the time being. We continuously have to watch the plot sizes and possibly the amount of log messages in the notebooks to prevent its resurrection though.
