### ISSUE TITLE
Double use of func name "dist_approx"

### ISSUE THREAD

**Issue by Evelyn-M** [CLIMADA-project/climada_python#220]
We're having 2 instances of the function `dist_approx`, once in the `util.interpolation`, once in the `util.coordinates` module, which is problematic as I want to merge the two modules eventually.
Reference tracker on the develop branch reveals that the interpolation.dist_approx is no-where else used, whereas coordinates.dist_approx is.

So, question 1, to the implementers of those funtions:
Better name suggested for the one in interpolation?

Question 2:
Do we need the interpolation.dist_approx? Where is it used? On a different branch?

**Comment by tovogt** [comment]
You can safely remove `u_interp.dist_approx`. It has originally been implemented for use in the context of tropical cyclone wind fields. By now, the function from `u_coord.dist_approx` is used for that purpose because it's more flexibel. Since we are using git, we can easily restore the function at any later time if needed (but I doubt it).

On a side note, don't remove the function `dist_sqr_approx` for now since it's used in `index_nn_approx` and can't easily be replaced. However, I would consider renaming it to `_dist_sqr_approx` to make clear that's only for internal use. It doesn't have a complete docstring and it seems to be tailored specifically for use in the context of `index_nn_approx`.

**Comment by Evelyn-M** [comment]
Alright! Thanks for the feedback!
