### ISSUE TITLE
Logging to file from other modules

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#265]
I have written python modules (or simple python code files) that import climada and use it. In these modules, I create a logger that is written to a file. So far so good.

The issue is that the CLIMADA logger is not redirected to the file but simply printed our in the console. Hence, if my application is running on a server and I want to look at the logs, the logging file does not show any of the climada logs.

My investigation suggests that this is because in the climada `climada.util.config.setup_logging` function, `LOGGER.propagate` is set to `False`, preventing the logger from propagating to upstream loggers.

- Can anyone confirm that setting propagate to False is the issue?
- What is the reason for setting propagate to False in CLIMADA?
- Do I have a way to have the climada logger redirected to upstream logger, e.g. loggers generated by `logging.basicConfig`?

**Comment by tovogt** [comment]
If CLIMADA propagated the logging, this would mean duplicated log outputs for many users. See here:
```
>>> from climada.util.config import LOGGER
>>> import logging
>>> logging.warning("hello from the root logger")
WARNING:root:hello from the root logger
>>> LOGGER.propagate = True
>>> LOGGER.warning("hello back from CLIMADA")
2021-08-04 10:07:15,008 - climada - WARNING - hello back from CLIMADA
WARNING:climada:hello back from CLIMADA
```
So, just propagating the logging is not an option if we don't want to start messing with the root logger's configuration from within CLIMADA.

In your situation, there are many ways to catch all of the log output. If the server has a job management tool, that tool might give you an option to log to a file (e.g [for SLURM]()). Alternatively, you can run CLIMADA from a shell script and use the redirection capabilities of your shell (e.g. [for bash](https://www.gnu.org/software/bash/manual/html_node/Redirections.html)). From within Python, you can [change `sys.stderr` and `sys.stdout`](https://stackoverflow.com/a/4675744) at the very beginning of your Python code (before making any other imports) to redirect to your log file. There is a [context manager](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) that helps you to do that temporarily.

If you really only would like to get the output from the `logging` module and no other sources (like `print` statements), you can directly modify CLIMADA's logger, by importing `LOGGER` from `climada.util.config` and adding or removing handlers according to your needs, or manually enabling log propagation if that really is what you want.

**Comment by petermkr** [comment]
I am experiencing similar problems with logging in CLIMADA. I am integrating it into my service as a library.

My main problem is that https://github.com/CLIMADA-project/climada_python/blob/main/climada/util/config.py is doing too much configuration for logging which I cannot control. 

For example, a logging handler is added to the CLIMADA-logger; the general recipe is to avoid this:
- https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
- https://docs.python.org/3/howto/logging-cookbook.html#adding-handlers-other-than-nullhandler-to-a-logger-in-a-library

I could reconfigure the logger after the config was read initially, but then I have to be very careful not to read the module again so that my reconfiguration will not be overwritten.

I think it would be good to extract the logging configuration from config.py and place it into a separate function which can then be called explicitly by the user if standard logging is needed.
For the default, it would be better if logging was configured as advised in the logging resources mentioned above.

**Comment by tovogt** [comment]
Yes, I agree that CLIMADA's default logging configuration is not Python's best-practice.

@emanuel-schmid @peanutfun @chahank Wouldn't this be something that you could look into as part of your task force activities? You would need to decide on whether changing the default logging behavior is something that would break CLIMADA for existing users, or whether backwards compatibility is not a priority when it comes to CLIMADA's logging behavior. The cleanest solution would really be to get rid of the log settings in `util/config.py` altogether and leave this entirely to users. It's not like there are reasons within CLIMADA that would require a specific log handler or formatter. It's actually very strange that CLIMADA defines its own logging handler and formatter since this looks very extrinsic to me. It reminds me of the 90s when web pages were changing the color of my browser's scroll bar...

**Comment by peanutfun** [comment]
Sounds straight-forward to me. The course of action to preserve the current logging behavior while following the logging best-practices seems to be as follows:
* Stop adding our own log handler in `util/config.py`. Simply create the logger there and set its formatter.
* Only use a single logger instance within Climada. Replace all `logging.getLogger(__name__)` by `logging.getLogger("climada")`.
* Set up the logger to report the current module name in every call with `%(module)s`, see https://docs.python.org/3/library/logging.html#logrecord-attributes. This will ensure the log messages look like before.
* Replace `climada.util.__init__.log_level` logic with a simple call to `logging.getLogger("climada").setLevel` (or similar).

Did I miss something? Would that resolve your issues, @petermkr?

**Comment by tovogt** [comment]
>     * Set up the logger to report the current module name in every call with `%(module)s`, see https://docs.python.org/3/library/logging.html#logrecord-attributes. This will ensure the log messages look like before.

No, I don't think that this is something that CLIMADA should do. Users can decide to do this by configuring their own preferred log handler and formatter.

**Comment by tovogt** [comment]
As I understand it, you can't adjust the log format without specifying a handler.

**Comment by emanuel-schmid** [comment]
@petermkr: thanks for bringing this up. It's obviously worth a discussion.

Now, before we completely restart the whole logging behavior in climada - what exactly do we want to achieve?

1) climada (as a library) should not add a Logging Handler upon initialization. Logging handlers should be in full control of the user. That's understood. 👍 

2) what else?

**Comment by peanutfun** [comment]
@petermkr Thanks for the detailed feedback! Do you think we could just use [`logging.basicConfig`](https://docs.python.org/3/library/logging.html#logging.basicConfig) for setting the defaults in Climada? It *does* add a handler but *only if* none was set for the root logger. Downstream users like you could then set their logging defaults *before* importing Climada (which would mean that the Climada-internal call to `logging.basicConfig` is ignored) or override the Climada defaults *after* importing it:

```python
# ---
# climada.__init__
import logging

from .util.config import CONFIG

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=CONFIG.log_level.str(),
)

# ---
# downstream.__init__
# Option 1: Set own defaults before importing Climada
logging.basicConfig(
    filename="my_log_file.log"
    level="DEBUG",
)
import climada

# Option 2: Override Climada settings
import climada
logging.basicConfig(
    filename="my_log_file.log"
    level="DEBUG",
    force=True,
)

```

**Comment by emanuel-schmid** [comment]
@petermkr: I like your suggestion a lot, the only trouble I see is that it is all but impossible to not set the `log_level` in conf/climada.conf. In general it is beneath the environment's site-packages files and having a local config file doesn't help because all undefined configuration values are backed up from there.

Therefore I'd suggest using a novel configuration value, e.g., `logging.climada_style` and do something like this:

```python
# climada.util.config.py

if CONFIG.logging.climada_style.bool():

    # every line in this conditional block is already part of the config module but unconditional

    LOGGER.propagate = False
    FORMATTER = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    CONSOLE = logging.StreamHandler(stream=sys.stdout)
    CONSOLE.setFormatter(FORMATTER)
    LOGGER.addHandler(CONSOLE)

    LOGGER.setLevel(getattr(logging, CONFIG.log_level.str()))
```

This should already do the trick: if you set that config value to `false` now, there is no Handler nor Formatter anymore, the logs are written to stderr, the "climada" logger is propagated to root and the level remains untouched.

**Comment by petermkr** [comment]
Thanks for your replies @peanutfun and @emanuel-schmid!
Both of your suggestions would solve our problems, so that's great!
I would rather go with the flag solution as it is crystal-clear that no logging at all is defined if you opt-out. For the `basicConfig` solution, users might fall prey to the rather unintuitive behavior of it (the first `basicConfig` call wins, unless you set `force=True`, and a CLIMADA import could then be already a `basicConfig` call).

**Comment by petermkr** [comment]
@emanuel-schmid Sorry for my late reply. I have looked at the PR, this should do the trick! 
Thanks a lot for the quick reaction. From my side, this ticket can be closed.
Probably this should also fix @bguillod's issue?
