### ISSUE TITLE
climada_petals config looking for removed vars in climada_python config

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#292]
When loading anything from `climada_petals` **main** one gets:

`ImportError: cannot import name 'setup_logging' from 'climada.util.config'`

and from `climada_petals` **develop**, one gets:

`ImportError: cannot import name 'remove_handlers' from 'climada.util.config'`

I think this is due to the cleaning here 4f91e2736c6a9a045ae25f79288b48a401df8ea5 but not sure whether it was too much cleaning in climada_python or too little cleaning in climada_petals.

**Comment by emanuel-schmid** [comment]
@aleeciu : Thomas is right, that's because the newest version of petals cannot cope with the newest version of climada_python yet.
This should be fixed by tonight. Then you have to update petals. Alternatively, you can downgrade climada_python to 2.2.

@tovogt : Not entirely sure about it, but the idea was that there are no handlers by default and removing them would only remove handlers that were explicitly added. And why should we interfere with a genuine wish for a particular logger? Like in case someone wants to collect logs in a separate file and analyze them for whatever reason.

**Comment by tovogt** [comment]
@emanuel-schmid That's a good reason! In that case, I suggest to remove the call to `remove_handlers` also from `climada_petals.util.config`.

I now see that you also removed `LOGGER.propagate = False`. I don't agree about that because this means that the logging is propagated to the root logger. If a user (or a different package) has set up the root logger with a console handler, then this will lead to double log outputs to the console, see this example:
```
>>> import logging
>>> import sys
>>> log = logging.getLogger()
>>> log.addHandler(logging.StreamHandler(sys.stdout))
>>> log.setLevel(logging.INFO)
>>> log.info("abc")
abc
>>> from climada.util.config import LOGGER
>>> LOGGER.info("abc")
2021-10-07 11:31:06,568 - climada - INFO - abc
abc
>>> LOGGER.propagate = False
>>> LOGGER.info("abc")
2021-10-07 11:31:27,129 - climada - INFO - abc
>>>
```
