### ISSUE TITLE
upgrade rasterio to 1.2.7

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#321]
rastrio 1.2.7/8 are more distinctive with regard to CRS comparison, some CRS that used to be equal (`util.coordinates.equal_crs`) are different now.

run `climada.util.test.test_coordinates.TestRasterMeta.test_points_to_raster_pass` and `climada.util.test.test_plot.TestFuncs.test_get_transform_3035_pass` to reproduce,

**Comment by chahank** [comment]
This is a rather important issue, as many CLIMADA methods rely on `util.coordinates.equal_crs` which fails in a non-obvious manner now.

**Comment by tovogt** [comment]
We had to get rid of the deprecated uses of `{"init": "epsg:xyz"}` and `"+init=epsg:xyz"` anyways. Instead, EPSG-based CRS should be specified simply as `"epsg:xyz"`. I fixed this in #322

**Comment by chahank** [comment]
Excellent! We now just have to update the test files (often named demo). @zeliest do you know whether all test files have already been added to the API or not?

**Comment by tovogt** [comment]
You mean that there are hdf5 files that are loaded in the tests and that have deprecated CRS specifications? I think this is low priority because I already included in my changes that CRS that are taken from a HDF5 file are corrected if they use a deprecated format: https://github.com/CLIMADA-project/climada_python/blob/f9df28c3a915df5845cea65b60b323291235abce/climada/util/coordinates.py#L1298-L1307

**Comment by chahank** [comment]
Oh, I missed that. Genius!

**Comment by emanuel-schmid** [comment]
@tovogt : awesome! 🙌
