### ISSUE TITLE
Mismatch TC category setter

### ISSUE THREAD

**Issue by mmyrte** [CLIMADA-project/climada_python#33]
There appears to be a mismatch between the [hurricane category setter](https://github.com/CLIMADA-project/climada_python/blob/c88b12087561c6c28d9b6b8152d9d98377e34897/climada/hazard/tc_tracks.py#L1583) and the [names](https://github.com/CLIMADA-project/climada_python/blob/c88b12087561c6c28d9b6b8152d9d98377e34897/climada/hazard/tc_tracks.py#L58); my IDE tells me it's only relevant for logging and plotting, but we may be mislabeling Cat1 as mere Tropical Depressions.

Can someone verify this before I fix the indices?

**Comment by tovogt** [comment]
After a quick scan through the code, I found that the differing scale is used in the random walk track generation in the calculation (and plotting) of the so-called "land decay" (the amount that wind speed is expected to decrease when a TC is over land). In those functions, there are several places, where the category is manually set using the constant `SAFFIR_SIM_CAT` instead of using `set_category`, for example:

https://github.com/CLIMADA-project/climada_python/blob/b282880910766f9eddd361f781720aaf40da3721/climada/hazard/tc_tracks.py#L1206

The TC category is not called `category` in those contexts, but `scale`. And the value is larger by 2 in order to use it as an index into `CAT_COLORS`, like here:

https://github.com/CLIMADA-project/climada_python/blob/b282880910766f9eddd361f781720aaf40da3721/climada/hazard/tc_tracks.py#L1469-L1470

In one of my last cleanup commits, I changed the `CAT_NAMES`:

https://github.com/CLIMADA-project/climada_python/blob/b282880910766f9eddd361f781720aaf40da3721/climada/hazard/tc_tracks.py#L59-L67

But you will still have two category scales internally because the `CAT_COLORS` list is indexed starting from 0 (since it's a list). If you really want to get rid of the two scales, you have to go through all the code for the random walk track generation and see which parts would be affected by this.

**Comment by mmyrte** [comment]
Ah, neat, thanks! Exactly what I would have done. I assume you've pushed that to develop? I didn't get to join the dev meeting yesterday; do you know when it'll be in master?

**Comment by tovogt** [comment]
Yes, that's on develop. As far as I know, there is still no definite agreement on when thinks are merged to master. But a release cycle of 3 months is currently discussed in the "coding convention" meetings.

**Comment by mmyrte** [comment]
Is the release cycle related to the semantic versioning, or to the branching model? To me, they are separate things. I thought I'd avoid those coding convention meetings, but it seems I'm too interested in the topic; I'll see you there I guess :)

**Comment by tovogt** [comment]
Forcing a merge from develop to master at each step of the release cycle is another part of the discussion. But it seems like we will enforce using separate branches for unfinished features to make sure that the develop branch is in a state that can be safely merged to master with every release.

**Comment by mmyrte** [comment]
@tovogt @chahank 

Chahan was asking on slack whether this could be documented [here](https://github.com/CLIMADA-project/climada_python/wiki/Upcoming-Releases) - Thomas, I didn't actually do anything other than fix the spelling on the labels. Would you say that something like this would do?

class _hazard.tc_tracks.TCTracks_: fix tropical huricane category labelling

**Comment by tovogt** [comment]
Yes, that's okay. (Note that I fixed a typo in your proposed line.)

**Comment by mmyrte** [comment]
Oh, thanks - that labelling/labeling thing always throws me. :)
