### ISSUE TITLE
shapefile.Reader can't cope with cartopy's changed shapefile format

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#353]
Cartopy's `shapereader.natural_earth` method read/writes files into the `~/.local/share/cartopy/natural_earth` directory, using a cache system that obviously checks for presence of the files and skips unnecessary writing.

When this file cache is emptied, and the method is called it writes new files, which have a different format than what they used to have back in 2020. The updated version of cartopy, 0.20, cannot be blamed, the same files are created with cartopy 0.18 and 0.19.

When the files in the new format are read with `shapefile.Reader` the result is heavily distorted, all strings have an arbitrarily sized series of '\x000' at their end, obviously because the `trim` method doesn't remove them properly. Also, the encoding seems to be different.

Suggestions on how to deal with this are welcome.

**Comment by emanuel-schmid** [comment]
My personal favorite would be to replace `shapefile.Reader` (or even the whole package) with cartopy's `shapereder` somehow.\
Is it possible? At what costs?

**Comment by tovogt** [comment]
Apparently, there are two changes at the same time:

1. There has been a new release of Natural Earth (v5.0.0) on 2021-12-08 (https://github.com/nvkelso/natural-earth-vector/releases/tag/v5.0.0). In the old versions, string fields used to be padded with spaces `\x20`. In the new version, string fields are padded with `\x00`. Apparently, this came as a surprise for `shapefile.Reader`: https://github.com/GeospatialPython/pyshp/commit/60b7aed05a0cd01e6c02bec0c5377d5988913571 But the new version also changes some of the contents, at least the ordering. For example, this check will fail now since the ordering of US states has changed: https://github.com/CLIMADA-project/climada_python/blob/2111c496a77cd2bad2f603f8e28adcf9c7914124/climada/util/test/test_coordinates.py#L589
2. Since cartopy version 0.20.2 (https://github.com/SciTools/cartopy/commit/6d787b01e122eea68b67a9b2966e45877755a52d), the `*.prj` and `*.cpg` files that were part of the Natural Earth files for many years, are not ignored (discarded) any more.  The `*.cpg` file contains the information about the encoding which has been `UTF-8` already for a long time (at least 5 years). Since the `*.cpg` was missing, the reader assumed the encoding to be `latin-1`. That's why we had a workaround for that:
https://github.com/CLIMADA-project/climada_python/blob/2111c496a77cd2bad2f603f8e28adcf9c7914124/climada/util/plot.py#L581-L584 By the way, this wasn't any different for `shapereader.Reader` (based on fiona) or `shapefile.Reader`. Now that the `*.cpg` file is present, we should change the code so that the workaround is only applied if really necessary... 

I agree that we should use `shapereader.Reader` instead of `shapefile.Reader` everywhere because it's usually faster. Here is my attempt to do this. However, I haven't run all unit and integration tests and can't guarantee that it's 100% working fine: https://github.com/CLIMADA-project/climada_python/pull/357

**Comment by emanuel-schmid** [comment]
🙌 Excellent! Thanks a lot, I'm running the full tests for #357

**Comment by chahank** [comment]
Thanks @tovogt and @emanuel-schmid  , I did not really have any knowledge about this issue.
