### ISSUE TITLE
Installation Link on Wiki Page Not Working

### ISSUE THREAD

**Issue by Sam-Herefordian** [CLIMADA-project/climada_python#375]
Hi all,

Clicking the Installation link on the Wiki page takes me to a 404 Not Working webpage.

I've found this link just by googling, presuming that it's what should be linked into it:
https://climada-python.readthedocs.io/en/stable/guide/Guide_Installation.html

Thanks in advance! Let me know if I've done anything wrong.

**Comment by emanuel-schmid** [comment]
Dear @Sam-Herefordian

Thanks a lot for the notification!
I have removed the installation link from the WIKI page, since there is already one in the [README.md](https://github.com/CLIMADA-project/climada_python#readme) (which points to https://climada-python.readthedocs.io/en/latest/guide/Guide_Installation.html).
There is always room for improvement when it comes to the documentation, but we're working on it. :smiley:
Best, Emanuel
