### ISSUE TITLE
unittest fiona circular import error

### ISSUE THREAD

**Issue by oweber-indtrack** [CLIMADA-project/climada_python#403]
Hello All, 

I have been following the installation instructions for conda, the unittest ran into this issue also raised in 
[fiona issue #944](https://github.com/Toblerity/Fiona/issues/944)

` with fiona._loading.add_gdal_dll_directories():
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)`

is there a fix or workaround for climada installation?

**Comment by emanuel-schmid** [comment]
Thanks for raising this.

Judging from previous experiences I suspect that you cannot import fiona itself in your environment?
Can you confirm this?
And also, can you confirm that you have installed climada-petals, in particular, that you have executed the command
`conda env update -n climada_env -f climada_petals/requirements/env_climada.yml`
?

If you can confirm both, the problem is exactly this step, that unfortunately ruined your environment. We're working on fixing this. Until then, the workaround is to remove the environment and reinstall it but skipping that step. 

Sorry for the inconveniences.

**Comment by oweber-indtrack** [comment]
Thanks Emanuel, I deleted the original environment (only core) and reinstalled, this time including climada-petals. I can confirm that I cannot import fiona while in climada_env, however a different pre-existing environment I have imports fiona without issue

`>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\anaconda3\envs\climada_env\lib\site-packages\fiona\__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "\anaconda3\envs\climada_env\lib\site-packages\fiona\collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed while importing ogrext: The specified procedure could not be found.`

**Comment by emanuel-schmid** [comment]
Ah. Sorry. I was thinking the other way around: in case you had already installed climada-petals, then remove the environment...
Never mind.

What is the output of `conda list fiona`?

**Comment by emanuel-schmid** [comment]
It turned out that the root source of this problem seems to be the gdal package on Windows, which is a dependency of e.g., geopandas.

The proposed workaround is to run the following commands:
```
conda activate climada_env
conda install gdal=3.4.0 -c conda-forge
```

Please post a note whether this works for you as well. If so, I'll update the the requirement files in this respect so that the installation instructions lead to a working environment.
