### ISSUE TITLE
A download warning in the impact_data tutorial

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#422]
My version of cartopy: 0.20.2
I was trying to run the following codes and got this warning
![impact_data 1](https://user-images.githubusercontent.com/71314575/163276276-d9388e87-6c6e-4fc8-9f51-07e7cc02ca75.png)
:

**Comment by peanutfun** [comment]
For some reason, [`DownloadWarning`](https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.io.DownloadWarning.html) is always issued by cartopy when it downloads data from the internet. This is therefore expected behavior 🤷 We could, however, [suppress the warning](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) in the respective CLIMADA code to avoid confusion.

**Comment by frqqyy** [comment]
> For some reason, [`DownloadWarning`](https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.io.DownloadWarning.html) is always issued by cartopy when it downloads data from the internet. This is therefore expected behavior 🤷 We could, however, [suppress the warning](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) in the respective CLIMADA code to avoid confusion.

I see, thank you very much!

**Comment by frqqyy** [comment]
> For some reason, [`DownloadWarning`](https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.io.DownloadWarning.html) is always issued by cartopy when it downloads data from the internet. This is therefore expected behavior 🤷 We could, however, [suppress the warning](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) in the respective CLIMADA code to avoid confusion.

The warning seems to have disappeared by itself... So I'll leave the file as it is now

**Comment by peanutfun** [comment]
I guess cartopy caches the download, so the warning will probably appear only occasionally
