### ISSUE TITLE
Different wind field results from new trop_cyclone.py

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#44]
I just updated develop and incorporated all changes made to the trop_cyclone module from June 11 on [](https://github.com/CLIMADA-project/climada_python/commits/develop/climada/hazard/trop_cyclone.py) 

problem is, after running the same analysis (i.e. using same centroids and tracks), I got two different answers between the previous version, and the new one.

previous:

<img width="443" alt="old_TC_results" src="https://user-images.githubusercontent.com/29018864/87684675-d2879c00-c782-11ea-8f71-49e23c1050e5.PNG">

current:

<img width="438" alt="new_TC_results" src="https://user-images.githubusercontent.com/29018864/87684697-d9aeaa00-c782-11ea-8a5a-aadb23648c60.PNG">

is this expected? if not, any idea of what is happening?

Thanks

**Comment by aleeciu** [comment]
changes I referred to here [https://github.com/CLIMADA-project/climada_python/commits/develop/climada/hazard/trop_cyclone.py](url)

**Comment by tovogt** [comment]
Let me first explain, what I did here: There were quite some bugs and unnecessary simplifications in the TC windfield computation in the version that you refer to as "previous". For example, the "previous" version pointed to some literature, but didn't actually implement the models described there. My changes make sure that the implemented code is actually in accordance with the documented models. Then, distance computation was done in a cartesian metric, even though the coordinate system is Lat/Lon. My updates use a spherical metric. This also makes sure that the code works for TC tracks crossing the 180/-180 longitude boundary. Finally, I did some literature research to have references for the non-documented parts of the code. A nice side-effect of the changes is that you now can get your hands on the directional wind speed vector field using the optional parameter `store_windfields`.

So, yes, a change of output is definitely expected. But hopefully, the change is quite small. For the two plots you posted, the color scale is quite different. You can't really tell from the plots how big of a difference you really have. In the unit tests, the difference was only at an order of magnitude of `1e-3` which shouldn't introduce significant qualitative or quantitative changes.

However, we should be careful with changes like these. Can you give details about the input data you used, produce plots with comparable color scales and maybe compute the quantitative difference?

**Comment by aleeciu** [comment]
I see, the changes you described can indeed change the final output.

To me, the very fact we have different colour bars tells you how much different results are - as I said, I used same tracks and same centroids, then the plotting function set the bar according to the range of the produced values.

anyway, here is a boxplot of wind intensity on Reunion at 1 km resolution from IBTrAC '2002017S07078'

<img width="301" alt="boxplot" src="https://user-images.githubusercontent.com/29018864/87690448-c5ba7680-c789-11ea-9a26-1eac276d640c.PNG">

would you like me to make a jupyter notebook and send it to you?

**Comment by tovogt** [comment]
Yes, that doesn't look good. No, don't bother, I can reproduce it. I will look into this tomorrow and try to trace it down.

**Comment by aleeciu** [comment]
Super! if you need any help or should you get a different result than I did do not hesitate to write me..

**Comment by aleeciu** [comment]
ps
maybe pick another area: to select Reunion (outermost French territory) I had to do some trick with the exposure generation - so don't waste time with that

alternatively, manually set centroids that work for the Reunion area

**Comment by tovogt** [comment]
After a quick look, I suspect that this is due to the "previous" code ignoring the radius of max wind information in IBTrACS and using a statistical estimate instead. The current code only uses the statistical estimate as a fallback if radius information is missing from the reported data. (The statistical model used in CLIMADA is known to be really bad because it's very hard to guess the radius of max wind from other storm features.)

**Comment by aleeciu** [comment]
mmhh I am not 100 percent sure, but I remember me doing some trials changing the rmw and the sensitivity of wind values to different rmw was really really low...

**Comment by tovogt** [comment]
I copied the `trop_cyclone.py` from version ad49dfd25833e2cd1ac9c3aef654136e68806b49 (June 11) as `trop_cyclone_old.py` to the current develop checkout and run the following notebook: https://nbviewer.jupyter.org/urls/pik-potsdam.de/~tovogt/climada/rmw_estimation.ipynb

While I was at it, I decided to switch the RMW estimation from quadratic back to a piecewise linear fitting curve. That's why you also find the "quadratic" fitting as a reference in the notebook. You can basically ignore all parts referring to "quadratic" since it doesn't really change the picture a lot and since it's now superseded anyways.

The result is definitely due to RMW estimation: Just look how the reported RMW (red) is almost twice as large as the estimated one (blue) and that is at the most intense phase of the TC:
![image](https://user-images.githubusercontent.com/57705593/87805718-17c8ce00-c856-11ea-899d-cdcbb5ff66cf.png)

However, overall, the distribution of wind intensities doesn't change that much:
![image](https://user-images.githubusercontent.com/57705593/87806524-501cdc00-c857-11ea-8eb3-f86dbe4f296a.png)

What changes is how the windfield is distributed spatially and this might affect Reunion a lot in this example:
![image](https://user-images.githubusercontent.com/57705593/87806640-7b073000-c857-11ea-8032-4d371ae2967e.png)

**Comment by tovogt** [comment]
And, the most eye-opening plot is the one comparing the previous model with the current model when enforcing both to use the estimated radii from the previous model:
![image](https://user-images.githubusercontent.com/57705593/87807563-af2f2080-c858-11ea-8666-bc21685e09c4.png)

**Comment by aleeciu** [comment]
Yes! thank you very much! 

Now I get it: overall it is not much of a change (see your boxplots) but, if your region of interest happens to be at the hedges of relevant wind values, then it does indeed make a huge difference (like it is for Reunion in this case - see my boxplot, which indeed referred only to the Reunion area).

This can be crucial: the 'previous' model e.g. does not simulate winds at Reunion from Cyclone Gamede (2007), which instead we know brought high winds and damages. The new version does! Good job, thanks!
