### ISSUE TITLE
Not-needed assignment of lon_normalize in tc_tracks?

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#523]
Hi,

I noticed the following line of code in `climada.hazard.tc_tracks`:
https://github.com/CLIMADA-project/climada_python/blob/7ed0adf6a15aef499060b3340b7925d7108979fc/climada/hazard/tc_tracks.py#L548

The documentation of `u_coord.lon_normalize` specifies that input are modified in place. Therefore, is the assignment really needed? I would assume the following would lead to the same result:
```
u_coord.lon_normalize(lons[lon_valid_mask], center=0.0)
```

or would this not work because only a subset of variable `lons` is passed as an argument?

There are two other such instances in `tc_tracks` on the dev branch:
https://github.com/CLIMADA-project/climada_python/blob/7ed0adf6a15aef499060b3340b7925d7108979fc/climada/hazard/tc_tracks.py#L1203
and
https://github.com/CLIMADA-project/climada_python/blob/7ed0adf6a15aef499060b3340b7925d7108979fc/climada/hazard/tc_tracks.py#L1367

Best,
Benoit

**Comment by tovogt** [comment]
In all those cases the caller loses hold of the array that is actually passed to `lon_normalize` because a new (sub-)array of an existing array is created in memory. And it's exactly for these use cases that `lon_normalize` chooses to return the changed array, even though it operates in place.

**Comment by tovogt** [comment]
I think, I have to correct myself. Strictly speaking, only the masked indexing produces a copy, the other two cases will only produce a view and assignment is actually not necessary. However, I'm not sure whether it's wise to omit the assignment because, in general, it's not transparent whether a particular indexing operation on a Pandas or Numpy object produces a view or a copy.

As a best-practice, I would recommend to be safe and always assign when applying an in-place operation to an indexed array or DataFrame. The gain in performance of omitting the assignment should be tiny.

**Comment by bguillod** [comment]
Thanks @tovogt for the very useful answer!
So what I take from it is that there is no performance loss in re-assigning in such a case.
