### ISSUE TITLE
Upgrade to Python 3.9+

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#596]
Is there a plan to switch to newer versions of Python? The conda environment files specifically require [Python 3.8](https://github.com/CLIMADA-project/climada_python/blob/develop/requirements/env_climada.yml#L27), which is 3 years old and has now been superseded by 3 major releases.

What would be required to switch to a newer version? I would be willing to help with that, but I'm not sure which steps to take.

**Comment by emanuel-schmid** [comment]
Since on Euler Python 3.9 is currently the only version where Climada 3.2 can be installed (without using conda), I assume updating to 3.9 may be "simply" a matter of editing the `requirements/env_climada.yml` file.

I haven't yet tested this assumption though. I have a hunch that it will take a few iterations before we find a working environment file for Python 3.9. And yet another round of iterations for Python 3.10 and so on.

Perhaps we eventually need to provide multiple environment files by Python version. 

In general I'd like to keep the lowest required Python version as steady as possible, because updating to a higher version may be prohibited by "company rules" - apart from the need to fix/change code.

However, I think the transition to a higher version will be smoother when we tackle the remaining `Future` and `Deprecation` warnings beforehand that arise when running Climada methods. That is an effort that won't be lost in any case.

**Comment by peanutfun** [comment]
Simply switching to `python=3.9` in `requirements/env_climada.yml` worked fine for me.

**Comment by emanuel-schmid** [comment]
settled with #614
