### ISSUE TITLE
San Salvador script failing

### ISSUE THREAD

**Issue by davidnbresch** [CLIMADA-project/climada_python#607]
the San Salvador script https://github.com/CLIMADA-project/climada_python/blob/main/script/applications/eca_san_salvador/San_Salvador_Adaptation.ipynb fails in cell 5 (FUTURE EXPECTED FLOOD DAMAGE): 

# expected annual impact
from climada.engine import CostBenefit

cb_acel = CostBenefit()
ax = cb_acel.plot_waterfall(haz_2015, ent_2015, haz_2040, ent_2040)
ax.set_title('Expected Annual Impact');

--> ValueError: 'assign_centroids' is set to 'False' but no centroids are assigned for the given hazard type (FL). Run 'exposures.assign_centroids()' beforehand or set 'assign_centroids' to 'True'

**Comment by davidnbresch** [comment]
..might be a good idea to re-assign centroids automatically to the actual hazard and throwing a warning, rather than abortiung with an error.

**Comment by emanuel-schmid** [comment]
All other plotting methods of `CostBenefit` somehow expect the user to previously run a `calc` beforehand. Imo that is probably "best practice". Hence I didn't propagate auto assignment in the other plotting methods in PR #640. _Ceterum censeo_ `CostBenefit` would be a good candidate for generous refactoring not unlike `ImpactCalc` .

However, there was another, hidden, issue with the SanSalvador scripts: the input excel sheet contained a 'cover' column for assets where all values were `0`. This is deprecated since the `ImpactCalc` refactoring (#436). So I deleted all entries (but not the column itself). Now it yields the same results as before.

**Comment by chahank** [comment]
Just a quick comment: a complete refactoring of `CostBenefit` and `Measures` is in planning.

**Comment by davidnbresch** [comment]
Thanks for fixing, now it works again, alas!
