### ISSUE TITLE
Invalid import in hazard.base.py

### ISSUE THREAD

**Issue by raphael-portmann** [CLIMADA-project/climada_python#632]
There is an invalid import in hazard.base.py of the `develop` branch which could be removed (see below)

```
     39 from rasterio.features import rasterize
     40 from rasterio.warp import reproject, Resampling, calculate_default_transform
---> 41 import sparse as sp
     42 from scipy import sparse
     43 import xarray as xr
```
this file: 

https://github.com/CLIMADA-project/climada_python/blob/d2441508f7dacb1d1642ef0db79bcd71555643c0/climada/hazard/base.py#L41

and the code on line 726 would have to be changed from
`sp.COO.from_numpy,`
to
`sparse.COO.from_numpy,`

**Comment by peanutfun** [comment]
We import two *different* modules here, [`scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html) and [`sparse`](https://sparse.pydata.org/en/stable/). The latter implements a sparse array format that implements the entire `numpy.ndarray` interface, which is why I introduced it in #578, see #544 for the discussion.

In summary (and *only* in `climada/hazard/base.py`!):
* `sparse` = `scipy.sparse`
* `sp` = `sparse`, NOT `scipy.sparse`

I agree that this is confusing but it was a way of not altering any other code using `scipy.sparse` in that file.

Finally, note that you need to update your conda environment if you encounter `ModuleNotFoundError: No module named 'sparse'`
