### ISSUE TITLE
Climate change implementation 

### ISSUE THREAD

**Issue by gamamou** [CLIMADA-project/climada_python#653]
I tried to forecast the expected annual impact (EAI)  under different RCP scenarios using different historical data (single event, historical data for 20 years, and historical data for 42 years). The reference year is 2055. I was expecting the gap to be minimal.  However, the results saw a significant gap as shown below. Any advice on best practices for selecting the optimal dataset to forecast future scenarios? 

Based on a single event (Irma 2017)
![image](https://user-images.githubusercontent.com/57597860/218365789-5898656d-c1ce-4f9f-8837-0d6316f4bdfe.png)

 Based on a 20-year historical data
![image](https://user-images.githubusercontent.com/57597860/218365910-1a804195-6629-486e-85dc-474106e65ab0.png)

 Based on a 42-year historical data 
![image](https://user-images.githubusercontent.com/57597860/218365979-7f1c94ae-54db-4fd7-b948-64a5f62eca6d.png)

**Comment by emanuel-schmid** [comment]
@gamamou Thanks for your interest in Climada.
Unfortunately we cannot help you with this question _here_ I'm afraid. Not just because we would need data and code and a more explicit description of what you try to achieve for helping you but also because this is not really an _issue_ with the Climada code but rather a question on how to use Climada best. If you can provide (minimal) data and code I'd suggest to try and ask a more concrete question on [stackoverflow](https://stackoverflow.com).
Good luck! 😃
