### ISSUE TITLE
Tests fail when run outside the CLIMADA working directory

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#665]
Tests fail when run from a directory other than the climada directory, because `CONFIG` cannot find the paths it's looking for. @peanutfun and I wondered whether this is expetected behaviour or not.

**Comment by emanuel-schmid** [comment]
Yes this is the expected behavior - to some extent. The basic installation test as described in the [Simple (installation) instructions 6.](https://climada-python.readthedocs.io/en/latest/guide/install.html#simple-instructions) is supposed to pass no matter where but the others depend on config values that are not defined in the default config file `climada/conf/climada.conf`.
If you want them to pass everywhere you can just move or copy the "test-config" file `./climada.conf` file to your home directory or to your working directory and if the test still fails, it's a bug. 😀

**Comment by peanutfun** [comment]
If I read the [docs on config files](https://climada-python.readthedocs.io/en/latest/guide/Guide_Configuration.html#Configuration-files) correctly, the `/climada.conf` is only read when working in this directory. Why are its contents not part of the "global" `/climada/conf/climada.conf`? I would expect the tests to always pass, independent from the working directory 🤔

**Comment by emanuel-schmid** [comment]
Just to restrict the "global" config to its essentials, without stuff that is not strictly required for using climada out of the box.
Tests are primarily meant for developers, so they can see what has been broken by their progress. The ordinary user doesn't need to run them.

**Comment by aleeciu** [comment]
Ok, I see it's intended behaviour and that there are good reasons for it. But would it make sense to throw a warning when tests are run from the "wrong" repo?

Currently, we get an error saying that CONFIG does not contain some of the sought paths, and it's not immediate at all to understand what is happening.

Maybe, when we try to load CONFIG and this fails, we can issue a warning like: "This likely happens because CONFIG cannot find the paths is looking for, use climada as wd or make sure CONFIG is properly modified".
