### ISSUE TITLE
Building Environment with Conda got Impossible

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#671]
By March 20, building the environment with _conda_ turned out to be impossible. More precisely: it takes longer than 6h.
What exactly the issue is is not known.

As a workaround, to keep automated testing possible, on Jenkins the build is now using _mamba_ instead of _conda_.

**Comment by peanutfun** [comment]
I cannot replicate the issue on my machine. Creating the environment with both conda and mamba works just fine for me. Which exact step takes longer than 6h for you?

**Comment by ThomasRoosli** [comment]
I experienced the same issue (building conda environment took longer than 6 hours) about two weeks ago. It was taking a long time to resolve the dependencies. On exactly the same system I retried it today and the issue was not there anymore. Maybe the issue does not appear anymore because something changed from the conda side...

**Comment by peanutfun** [comment]
As the conda-forge repository experiences a lot of updates and conda has some trouble resolving a large set of dependencies, it seems to me like this issue comes up somewhat regularly. It also seems to resolve itself after the next (round of) updates to conda-forge.

In the meantime, I can recommend using [Mamba](https://mamba.readthedocs.io/en/latest/), which is much faster and has less trouble resolving dependencies.

I think it's safe to close this issue now. Feel free to reopen if you disagree 🙃
