### ISSUE TITLE
Make `conda install climada` the default installation instruction

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#673]
Climada is now available via conda-forge: https://anaconda.org/conda-forge/climada

This means that the tedious dependency installation before running `pip install climada` can now be dropped in favor of the much simpler `conda install -c conda-forge climada`. To get to the same result as with the current [simple installation instructions](https://climada-python.readthedocs.io/en/stable/guide/install.html#simple-instructions), one now has to execute a single command:

```
conda create -n climada_env -c conda-forge climada
```

This will install Climada and all its dependencies into a new `climada_env` environment.

Proposals:
* Add `conda install -c conda-forge climada` as installation instruction in the README
* Rewrite the [Simple Instructions](https://climada-python.readthedocs.io/en/stable/guide/install.html#simple-instructions) to simply use  `conda create -n climada_env -c conda-forge climada`

**Comment by emanuel-schmid** [comment]
👍 Very nice, indeed!
But before we change the default installation instruction we have to tackle some dependency issues I'm afraid:

- #678 
- `climada.hazard.test.test_tc_tracks.TestIO.test_hdf5_io` fails
- `climada.hazard.test.test_tc_tracks.TestIO.test_to_geodataframe_line` fails but can be fixed with commit fa75338
- `climada.engine.unsequa.test.test_unsequa.TestOutput.test_plot_unc_cb` fails
- `climada.test.test_litpop_integr.TestAdmin1.test_brandenburg` and `test_netherlands150_pass` fail

**Comment by emanuel-schmid** [comment]
PR #682 fixes all failing tests with the exception of the ones from #678 .

**Comment by emanuel-schmid** [comment]
Maintenance of the conda-forge installation may get demanding. 
We more than likely need to make restrictions in the dependency versions, for domain reasons but also for technical reasons: on my computer I am not able to run `python build_locally.py` successfully: it takes an unknown amount of time (>5h) to eventually crash, possibly for memory reasons.
With most dependency versions fixed, it still requires significant amounts of time, cpu and memory.

**Comment by peanutfun** [comment]
`python build_locally.py` is not required. The conda-forge CI pipeline automatically tries to build all PRs submitted to https://github.com/conda-forge/climada-feedstock

**Comment by peanutfun** [comment]
Resolved by #714
