### ISSUE TITLE
time_step in TC tracks with inconsistent units

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#73]
Hi,

I **THINK** I noticed an inconsistency in the definition of time_step in TC tracks:
* In read_ibtracs_netcdf, time_step is defined in '**seconds**' (typically, 10800 which is 3h in seconds, 3*60*60).
* In equal_timesteps, time_step is defined in 'hours'.
* in read_file_emanuel, my understanding is it's in hours
* In read_one_gettelman, I think it's in hours, too.
* In _read_ibtracs_csv_single, I don't know.

This is an issue, because time_step is used in compute_windfields, more specifically:
- _vtrans
- _bs_hol08
@tovogt Do I guess correctly that for the holland wind model part, time should be in hour? We have to be 100% sure of that and I guess you're best placed to know/check this.

Can someone please check
1. Whether I am correct? If so I guess it's a matter of correcting read_ibtracs_netcdf.
2. Whether there are other usages of 'time_step' in a TCtracks (or TropCyclone) object.

Essentially this wouldn't impact the result if equal_timestep is applied before doing anything else. But if not, translation speed would be great underestimated. That is my guess so far.

I discovered this while attempting to make the random walk application independent of the timestep. I then got tracks all over the world if using data before applying 'equal_timestep' ;-)

Thanks

**Comment by tovogt** [comment]
Yes, it's a bug that I noticed about 2 weeks ago when I was working on the `feature/tc_tracks_io` branch. I actually fixed it silently there, but forgot to change it in develop: 

https://github.com/CLIMADA-project/climada_python/blob/6517967c57aa5d3ed79aaf5865674927f51e3e14/climada/hazard/tc_tracks.py#L332-L333

Most people are using the `equal_timestep` feature, so nobody ever noticed it before. Fixed in 0a18b89

**Comment by bguillod** [comment]
Perfect, thanks!
