### ISSUE TITLE
Numba issues in TCTracks.calc_random_walk

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#76]
Running `TCTracks.calc_random_walk` the package `Numba` issues a series of warnings. Can the author (I think it is  @tovogt who rewrote the calc_random_walk) please have a look and comment on these warnings?

If the warnings actually mean that Numba is not able to use this code, then either the code must be adapted of Numba removed.

**Comment by chahank** [comment]
@tovogt  Could you please have a look at the pull request #78 and comment on the use of `Numba` decorator `@jit(parallel=True)` on `_one_rnd_walk`? Basically, do you know whether the issue is there due to a misplaced use of `@jit(parallel=True)` and it can those be removed, or is there some deeper reason for it to be there?

**Comment by tovogt** [comment]
The warnings are not due to any changes introduced by me. Actually, I didn't rewrite anything, but only moved the code from one source code file to another without touching any functionality. It's a relatively new Numba feature that users are warned when Numba falls back to object mode, and the reasoning behind this is desribed here: https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit Instead of removing the decorator, you can use `forceobj=True` to get rid of the warnings. But if you have the experience that the use of Numba in this particular place doesn't boost performance substantially, you might just as well remove the decorator. Since I'm not using the random walk feature, I can't give any recommendations.

**Comment by chahank** [comment]
Thanks a lot for the feedback @tovogt ! This is very helpful. @bguillod We thus might remove the numba decorator where there is the warning as in my experience the method is fast enough.

**Comment by bguillod** [comment]
I agree, so I'll remove the numba decorator there.

**Comment by bguillod** [comment]
I've removed the @jit decorator for `_one_rnd_walk` in 82ce921aa16e2c7de8e277ebd3043bce9fb20e07.

**Comment by bguillod** [comment]
The fix has been merged into develop.
