### ISSUE TITLE
Goodbye Stamen

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#796]
Stamen has been removed from the Tiles providers listed in xyzservices by 2023.10.1
https://github.com/geopandas/xyzservices/releases/tag/2023.10.1

This breaks the installation test because `climada.engine.impact.Impact.plot_basemap_XXX_exposure` use `ctx.providers.Stamen.Terrain` as default.

Short term solution (de-corrupt the environment on Jenkins): [pin xyzservices version to 2023.10.0](https://github.com/CLIMADA-project/climada_python/commit/c8a05872c9cd7c67655b269799b123b0489f692f)

Long term solution: pick another default.

**Comment by peanutfun** [comment]
@emanuel-schmid This solution does not help because Stamen will remove their tiles from their old service provider by 31 October. Even when you pin xyzservices you will not be able to download the basemaps the old way.

The Stamen maps are still available via the Stadia provider, but that requires a personal API token after a free registration with Stadia, unfortunately.

I suggest we switch to `CartoDB.Positron`, which uses very few colors and therefore should be suited for plotting colors onto it.

**Comment by emanuel-schmid** [comment]
@peanutfun The short term solution only addresses the failing environment build on Jenkins, not the Stamen tiles being withdrawn.

**Comment by peanutfun** [comment]
Very good, I did not realize the problem was that severe.

**Comment by peanutfun** [comment]
Resolved by #798
