### ISSUE TITLE
Impact read hdf5 fails if hazard event name is not a string

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#807]
Similarly to issue #789 , saving an impact to hdf5 if the hazard name is not a list of strings causes issues when the data is read again. 

Precisely, the attribute `impact.event_name` must be a list of strings at the moment of saving to hdf5 `impact.to_hdf5`, or the reading method `impact.from_hdf5` should be able to handle non-numerical values.

**Comment by peanutfun** [comment]
This is *not* an issue with writing, but with reading: https://github.com/CLIMADA-project/climada_python/blob/e41222210bfb99e92829c0a86f1db2f31355abf5/climada/engine/impact.py#L1246

Because "event_name" was always specified as a list of strings, I wrote code that *only* reads it as such. We could adapt that, too.

**Comment by chahank** [comment]
Well, the fact is that we do not enforce type on the impact objects. So, either we need to change that or update the over-restrictive read method.

**Comment by peanutfun** [comment]
@chahank @sarah-hlsn

**Comment by peanutfun** [comment]
> Do we want to read other values than strings or do we want a better error message if the values are not strings? What do we do in this case? Continue by setting "default" event names or only throw an error?

@chahank This does not seem to be a pressing issue so I would like us to take a pragmatic decision here and resolve it.

**Comment by chahank** [comment]
Agreed!

**Comment by peanutfun** [comment]
#894 proposes a solution that reads other data types, but issues a warning that `event_name` cannot be decoded

**Comment by peanutfun** [comment]
Decision from discussion in https://github.com/CLIMADA-project/climada_python/pull/894:

* We only *write* an Impact object if `event_name` contains strings exclusively. If it does not, we throw an error instead of writing.
* When *reading*, we expect strings stored in `event_name`. If they are not, we throw a warning and all `str()` on each element, potentially ending up with nonsensible values. But `event_name` is ensured to be strings after reading.
