### ISSUE TITLE
Fiona Error on fresh installs

### ISSUE THREAD

**Issue by lukasludescher** [CLIMADA-project/climada_python#836]
Hi,

I have run into a somewhat fatal error when installing Climada (Version 4.0.1) anew, using both the easy instructions, as well as the advanced instructions.

Upon running the line 'python -m unittest climada.engine.test.test_impact' in the VSCode terminal within the dedicated Climada environment, the following error occurs:

```
CPLE_AppDefinedError                      Traceback (most recent call last)
File fiona\crs.pyx:585, in fiona.crs.CRS.from_epsg()

File fiona\_err.pyx:265, in fiona._err.exc_wrap_int()

CPLE_AppDefinedError: PROJ: proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, 
area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name

File fiona\crs.pyx:1265, in fiona.crs.from_epsg()

File fiona\crs.pyx:589, in fiona.crs.CRS.from_epsg()

CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name

```

I tried to solve the error (while keeping the latest version of Climada) by installing Climada fresh in VSCode again using simple and advanced instructions, but to no avail. Similarly, I tried to install it on a dedicated Miniconda-Kernel and run it on Jupyter Lab, but the issue persists. Have others observed similar issues?

My current workaround:
Fixing GDAL and PROJ versions to the ones reported when installing fiona 1.9.1 on a pristine Python kernel (checked GDAL&PROJ versions with fiona install on Python 3.8, 3.9, 3.10). This downgrades Climada and Climada Petals to versions 3.3.2. Further, the hotfix for stamen needed to be applied, pinning the xyzservices to version 2023.10.0.

Any insight is greatly appreciated.^^

Kind regards

**Comment by peanutfun** [comment]
This looks like an error within the version of Fiona you were using. Our only remedy would be to restrict the versions in our environment until this is fixed "upstream". Could you please report which version combination of fiona, gdal, and proj works for you? For which version of fiona did you receive the original error?

**Comment by lukasludescher** [comment]
Hi,

Sorry for the late response, it took some time to come around and checking the package versions again. For the 'broken' install where these errors occurred, the package versions are as follows:

- fiona 1.9.1
- gdal 3.6.2
- proj 9.1.1

The package versions that 'fixed' the issue are the following:

- fiona 1.8.22
- gdal 3.5.2
- proj 9.0.1

This process unfortunately leads to a downgrade in the Climada version.

Kind regards

**Comment by peanutfun** [comment]
@lukasludescher Thanks for reporting back. Looking through the Changelogs of these packages, I cannot find a possible source for your error. It seems to be related to an interaction between Fiona and Proj. Therefore, there is little we can do from Climada's side of things. If the error persists for newer versions of Fiona, I suggest you raise an issue in the respective repository.

However, while investigating, I noticed that the Climada requirements specify a version of Proj, but not for PyProj. This seems like a possible source of issues to me, because we explicitly require PyProj in the code, and it usually packs a version of Proj. @emanuel-schmid, might there be a particular reason for that? If not, I would try to update the requirements and hope that setting a version for PyProj will avoid issues as reported here in the future.

For reference, see [feedstock recipe](https://github.com/conda-forge/climada-feedstock/blob/0f2ede03aae3674b9de280dfedc393506d974837/recipe/meta.yaml#L45) and environment specs: https://github.com/CLIMADA-project/climada_python/blob/1300e3d9dffd51c9d5f474255d56416495d4b7f1/requirements/env_climada.yml#L25

**Comment by emanuel-schmid** [comment]
@lukasludescher The package versions of the 'broken' install,
- fiona 1.9.1
- gdal 3.6.2
- proj 9.1.1
are the exact versions that the current environment on jenkins (Linux) as well as the local dev environment on my computer (Windows) have installed - without problems, so far.
Therefore I suppose that - even though downgrading solved the problem - these versions were not the source of it.

@peanutfun I cannot right away see how pinning `pyproj` instead of `proj` is preferable. Judging from the dependency tree I'd rather expect `proj` causing a mess, as it is also a dependency of `rasterio`, `gdal`, `geotiff` and `libspatialite`.

**Comment by peanutfun** [comment]
> Judging from the dependency tree I'd rather expect proj causing a mess, as it is also a dependency of rasterio, gdal, geotiff and libspatialite.

@emanuel-schmid Point taken. Nonetheless, I would like to add `pyproj` to the explicit dependency list. For now, it seems to work that Mamba determines a suitable version of `proj`, see #845. I prefer keeping it that way and only adding a version restriction of `proj` if something breaks.

**Comment by lukasludescher** [comment]
@peanutfun, @emanuel-schmid 

Hi,

Indeed, it seems to be an issue that is purely occurring with my machine and the topic could be closed on my account. I don't mind working with the downgraded version for now until I will perform a fresh install of the os when time and circumstance allow for it. 

Thank you for your effort!

**Comment by peanutfun** [comment]
@lukasludescher Thank you for reporting back. I'll close this issue then.
