### ISSUE TITLE
Links in tutorials within the doc do not work (the ones on the right side navigation bar are ok)

### ISSUE THREAD

**Issue by davidnbresch** [CLIMADA-project/climada_python#862]
Links in tutorials within the doc (usually at the top, in the kind of index) do not work (the ones on the right side navigation bar are ok)

**Comment by emanuel-schmid** [comment]
Thanks for bringing this up. 
The inner-document links of Jupyter Notebooks are not uniformly written throughout the climada tutorials and guides, and whether they work or not depends on how the notebook is opened. Some of them do actually work when the tutorial is opened through Jupyter itself, but not in the html documents generated from the notebooks.
I'm still thinking it should be possible to make them work in both, notebook and html documents and will give it a try. But if not - I guess the html documents have higher priority - right?

**Comment by peanutfun** [comment]
> I guess the html documents have higher priority - right?

Since @davidnbresch refers to a "right side navigation bar", I think he was accessing the online HTML docs. Since these and also many IDEs automatically create document navigation bars, I am in favor of removing these custom TOCs at the top of the documents altogehter. But I agree, there should be a way to make these links work consistently. How to continue?
